export const portfolio_paths = ["/projects/portfolio/1.png"]
export const ecom_paths = ["/projects/ecom/1.png", "/projects/ecom/2.png", "/projects/ecom/3.png", "/projects/ecom/4.png"]
export const chessle_paths = ["/projects/chessle/1.png", "/projects/chessle/2.png", "/projects/chessle/3.png"]
export const graphtool_paths = ["/projects/graphtool/1.png", "/projects/graphtool/2.png", "/projects/graphtool/3.png"]
export const deliveryapp_paths = ["/projects/deliveryapp/1.png"]
export const travelapp_paths = ["/projects/travelapp/4.jpg"]
export const quick_translate_paths = ["/projects/quick_translate/1.png"]
export const hrm_paths = ["/projects/hrm/1.png","/projects/hrm/2.png","/projects/hrm/3.png","/projects/hrm/4.png","/projects/hrm/5.png"]
